### ISSUE TITLE
Add reorientation to RPI also for train/val transforms

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/contrast-agnostic-softseg-spinalcord#103]
Currently, reorientation to RPI is explicitely specified only for `inference_transforms`:

https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/59e6229a32fa68b20d8fae6e4cb73cd07a7a243b/monai/transforms.py#L44

This makes sense because spine-generic images used for train/val were already reoriented to RPI before training. So we need to reorient to RPI only images we run inference on.

But, with new data coming to the training, it would be a good idea to use `Orientationd(keys=["image", lbl_key], axcodes="RPI")` also for `train_transforms` and `val_transforms`.

**Comment by naga-karthik** [comment]
Thanks for opening the issue! I missed this when creating release `v2.1` -- this will be fixed in the next release!

**Comment by naga-karthik** [comment]
closing as this is the default now and has been fixed
