### ISSUE TITLE
run_inference_single_image.py v1 vs v2

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#106]
is the 'non v2' file obsolete? if so can we get rid of it? If not, why do we need both versions?

![image](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/2482071/bcbd5094-16eb-49b0-90c3-ef3518527ad3)

**Comment by naga-karthik** [comment]
oh, actually `run_inference_single_image.py` is _the_ file. The `_v2` is obsolete. 

This is a bigger issue (for me) -- sometimes I need to heavily modify the original inference script to do some testing. BUT, I don't want to keep it local (easier to reference it when it is pushed) and don't want to break the original inference script if someone (like yourself in this case) is using it. 

SO, how to go around this issue? This is the reason I created `_v2` file.

**Comment by naga-karthik** [comment]
okay, I realized the `_v2` file is on `main` so it's my fault it's on the main branch! I think files like these should be in branches (i.e. experimental). I am going to remove it from `main`
