### ISSUE TITLE
Inconsistent list of subject used for training

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#109]
[This list of subject](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/32ef5c9d541bb779453cca6fc8c25b768bc2c9b1/monai/data_split_all_soft_seed15.yaml) is 5 months old, and it seems inconsistent with [release 2.4](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.4), which includes additional data bases.

**Comment by jcohenadad** [comment]
Related to this, another, probably stale, instruction from this other README: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/main?tab=readme-ov-file#42-datalist-creation

**Comment by naga-karthik** [comment]
Hmm, I wasn't sure if I could update the list of subjects. Some of the datasets that were used for release 2.4 are private and I don't know if I can upload the subjects list on GitHub?

**Comment by jcohenadad** [comment]
> Hmm, I wasn't sure if I could update the list of subjects. Some of the datasets that were used for release 2.4 are private and I don't know if I can upload the subjects list on GitHub?

I'm talking about listing the name of the subjects-- not the data. Essentially, we should be able to reproduce your model (and to be able to do so, we need the list of subjects for train/valid/test)

**Comment by naga-karthik** [comment]
Ah okay! I misunderstood! 

That reminds me -- the main branch is up-to-date because I'm still developing the model (i.e. trying to improve the performance on compressions, although not at the moment, but I will get to it). Because of this all the latest updates in the branch `nk/new-model` and in [this folder](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/nk/new-model/datasplits) you can find the all the information about the datasets and splits used.

**Comment by naga-karthik** [comment]
I am also unsure what to do with the branch actually. I thought this branch will lead to a new model (ie in a different publication where the model is trained on several other datasets). BUT, it is likely going to be delayed because of the revisions for the original contrast-agnostic MedIA paper

**Comment by jcohenadad** [comment]
> That reminds me -- the main branch is up-to-date because I'm still developing the model 

I'm not sure I understand the logic here. The main branch is _not_ up to date, see e.g. https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/109#issue-2346694612.

> Because of this all the latest updates in the branch nk/new-model and in [this folder](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/nk/new-model/datasplits) you can find the all the information about the datasets and splits used.

OK I understand the issue now. You're working on a branch that is more recent than the `main` branch, and your release was based of your branch `nk/new-model` instead of from the `main` branch. This is not the proper git workflow and leads to confusion.

The proper workflow is:
- you work on branch A
- once you're happy with your dev, you merge to main branch
- you delete your branch
- you release (from branch main)
- more dev to do? you open a new branch B
- and so on...

**Comment by naga-karthik** [comment]
> The main branch is not up to date, s
