### ISSUE TITLE
Re-run preprocessing to include combinations of contrasts

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/contrast-agnostic-softseg-spinalcord#112]
## Description

To repsond to R2.4, we need to rerun preprocessing so thta the average GT includes combinations of the following contrats:

* T2w (already hard GT)
* T2w + T1w
* T2w + T1w + DWI
* T2w + T1w + DWI + gre_t1w
* T2w + T1w + DWI + gre_t1w + T2*w
* T2w + T1w + DWI + gre_t1w + T2*w + mt_on (already have)

**Comment by naga-karthik** [comment]
Closing as this has been completed!
