### ISSUE TITLE
`nnunet_mednext` is not listed in `monai/requirements.txt`

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/contrast-agnostic-softseg-spinalcord#114]
`nnunet_mednext` is not listed in https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/main/monai/requirements.txt

https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/ad7ee3d5ac37d22454d0a0e397c43f54f081a61d/monai/run_inference_single_image.py#L30

```bash
python monai/run_inference_single_image.py -h
Traceback (most recent call last):
  File "monai/run_inference_single_image.py", line 30, in <module>
    from nnunet_mednext import MedNeXt
ModuleNotFoundError: No module named 'nnunet_mednext'
```

Temporary fix: I commented [L30](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/ad7ee3d5ac37d22454d0a0e397c43f54f081a61d/monai/run_inference_single_image.py#L30) because I wanted to use the default `--model monai` (and not `mednext`).

**Comment by naga-karthik** [comment]
thanks for opening the issue, Jan! Just deleted all the instances of mednext in commit https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/commit/bbcb45644b3fa2ac1d14ff6a4f5be935d580273f in a new branch `nk/contrast-agnostic-v2`

**Comment by naga-karthik** [comment]
closing as will be fixed in the (very) near future in the next release
