### ISSUE TITLE
Remove `datasplit_sci-zurich_seed50.yaml` from `v2.4` tag

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/contrast-agnostic-softseg-spinalcord#120]
As clarified in [this comment](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/118#issuecomment-2410171309), the `sci-zurich` dataset was NOT used during v2.4 training.
Thus, we should remove `datasplit_sci-zurich_seed50.yaml` from the [datasplits](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/v2.4/datasplits) folder for the v2.4 tag to avoid future confusions. 

Steps to do so suggested by chatGPT: https://chatgpt.com/share/670d2daf-bd6c-8008-8c0d-0e024edad032

**Comment by naga-karthik** [comment]
Thanks for opening the issue and the chatgpt commands! those were really useful! [Fixed now](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/v2.4/datasplits)
