### ISSUE TITLE
Release strategy for models

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#123]
naming of models: https://github.com/ivadomed/ivadomed/wiki/repositories#packaging-models

No need for pre-release. If you have a new model, just release it.

**Comment by naga-karthik** [comment]
thank you for linking the release strategy! updated [here](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.5)
