### ISSUE TITLE
Training separately on the two `MTS` contrasts

### ISSUE THREAD

**Issue by uzaymacar** [sct-pipeline/contrast-agnostic-softseg-spinalcord#25]
The `spine-generic-processed` dataset include `acq-MTon_MTS` and `acq-T1w_MTS` contrast. As noted in the [previous meeting](https://docs.google.com/document/d/1JS_wzbm3WiofrUT1sVu9ceoWTMYHrPokgfIn2f2RoGc/edit#heading=h.dv7edljgzemj), these contrasts were not picked by `pybids==0.15.1`. We discovered two solutions to the problem:
1. Add the subject paths to `force_index` similar to how it is done for microscopy and CT [at these lines](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L83-L108)
2. Upgrade to `pybids==0.15.2` which introduced `MTS` support and rename the files according to https://github.com/spine-generic/data-multi-subject/issues/116.

However, in both of these solutions, the ivadomed loader with `pybids` considers *the last part of the filename (after the last underscore) as the modality* as mentioned [here](https://github.com/ivadomed/ivadomed/pull/699#issuecomment-795911036). This means the two contrasts are treated as one in effect as both have the suffix `MTS`. 

To train separately (which I assume is the goal), it looks like we would have to use different suffixes. However, this doesn't look like a clean solution and I am open to any other suggestions!

**Comment by jcohenadad** [comment]
To me this is a limitation of `ivadomed` and the problem needs to be fixed there, sooner rather than later. Ongoing discussions:
- https://github.com/ivadomed/ivadomed/issues/1102
- https://github.com/ivadomed/ivadomed/issues/1087
- https://github.com/ivadomed/ivadomed/issues/1009

**Comment by uzaymacar** [comment]
Below are the BIDS-compliant files we need to support (on the right) and their older names (on the left):
```
acq-MTon_MTS → flip-1_mt-on_MTS
acq-MToff_MTS → flip-1_mt-off_MTS
acq-T1w_MTS → flip-2_mt-off_MTS
```

**Comment by jcohenadad** [comment]
The issue with the ivadomed loader will be addressed here: https://github.com/ivadomed/ivadomed/pull/1240

**Comment by naga-karthik** [comment]
I see that the file names have been changed but not updated in the ReadMe yet. @sandrinebedard could you please briefly describe it in the ReadMe? Thanks!

**Comment by sandrinebedard** [comment]
I removed all instances of training with ivadomed, where is mentionned the MTS contrasts.
