### ISSUE TITLE
Remove extreme slices in the T2w space to avoid partial segmentations

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#33]
In relation to https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/pull/32, the new results produce partial images in the destination (T2w) space (see last slice):

![image](https://user-images.githubusercontent.com/2482071/192327899-962e7516-eb7c-45f7-9e5f-f89fe25bd970.png)

This is problematic because:
- the registration algo is unreliable (because partial seg in source vs. complete seg in the destination)
- the output softseg will be ulgy

Solution?
- We need to crop 2-3 slices from the registered coverage image (eg: `sub-brnoUhb05_acq-T1w_MTS_ones_reg.nii.gz`), and then add in the analysis pipeline a multiplication of the registered segmentation and of the registered coverage image.
- How do we detect the slices to remove? we could create an algo that finds the minz/maxz that have at least one non-null voxel in the registered segmentation, and that will be the minz/maxz from which to crop 2-3 slices.

**Comment by sandrinebedard** [comment]
closed with https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/pull/32
