### ISSUE TITLE
freeze version for OHBM

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#37]
todo:
- merge ae/ohbm to master
- create resease asap, in the release note mention that this code was used for the ohbm submisssion
- update README to make sure process/training is reproducible (eg: link to config files, etc.)

**Comment by naga-karthik** [comment]
Not sure if this was done for OHBM, but a release was created for MICCAI (which is not up-to-date anymore, hence not linking)

Another release for the final model will be created for the MedIA submission, hence closing this.
