### ISSUE TITLE
Filtering not effective

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#38]
https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/1976cec36162f8dd1ce200cee13a3bf5493cbd9c/config_templates/meanGT_soft.json#L36-L38

see: https://github.com/ivadomed/ivadomed/issues/1234

**Comment by naga-karthik** [comment]
This is not relevant anymore as we're going with the monai training.
