### ISSUE TITLE
Optimize DA

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#45]
https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/1976cec36162f8dd1ce200cee13a3bf5493cbd9c/config_templates/meanGT_soft.json#L118

Ideas: artifacts, eg:
- [RandomMotion](https://torchio.readthedocs.io/transforms/augmentation.html#randommotion)
[RandomMotion](https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomMotion)
[RandomGhosting](https://torchio.readthedocs.io/transforms/augmentation.html#randomghosting)
[RandomGhosting](https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomGhosting)
[RandomSpike](https://torchio.readthedocs.io/transforms/augmentation.html#randomspike)
[RandomSpike](https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomSpike)

**Comment by naga-karthik** [comment]
We're sticking with the following data augmentation methods: 

<details>
<summary> Training </summary>

<img width="802" alt="Screen Shot 2023-08-22 at 9 15 15 AM" src="https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/5fa64fcb-11fb-4530-97fd-f20c4d5d8b7b">

</details>

<details>
<summary> Validation/Testing </summary>

<img width="681" alt="Screen Shot 2023-08-22 at 9 15 55 AM" src="https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/fe764d41-aa08-4e5d-aa9f-1a43a44bd792">

</details>

I have noticed that adding more augmentations only increases the time per epoch with incremental improvements in performance.

**Comment by naga-karthik** [comment]
Here are the data augmentation transforms for the final model:

<details>
<summary> Training </summary>

![Screen Shot 2023-10-05 at 11 33 39 AM](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/f69862b4-bd8f-423a-bcdf-8f8ee0bffa60)

</details>

<details>
<summary> Validation/Testing </summary>

![Screen Shot 2023-10-05 at 11 35 02 AM](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/7ea91147-723d-4ec8-9a1d-367c4d348042)

</details>
