### ISSUE TITLE
Train on with other seeds 

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/contrast-agnostic-softseg-spinalcord#48]
Currently, our mdoel is only trained for one seed , 15, would be good to test other seeds.

**Comment by naga-karthik** [comment]
Yeah, this has to be done but we can't our results with ivadomed anymore if we change seeds. We can only do a comparison between nnUNet and MONAI (which could be a comparison between hard and soft labels).

**Comment by sandrinebedard** [comment]
Also redo a STD per subject for each seed to get more subjects in the violin plot

**Comment by naga-karthik** [comment]
Just a quick note of clarification -- choosing different seeds might result in a slight overlap of test subjects coming from each seed. While we will surely have more points in the STD CSA plot, it will simply not be `num_seeds x num_test_subjects` (i.e. we would have to remove some repeated subjects)
