### ISSUE TITLE
Try with much smaller patch sizes (based on nnunet recommended size @ebadrian ?).

### ISSUE THREAD

**Issue by louisfb01** [sct-pipeline/contrast-agnostic-softseg-spinalcord#55]
Run nnUnet on the uncropped dataset to have ideal patch size.

**Comment by naga-karthik** [comment]
Update: patch-size from nnunet was not ideal, hence we stuck the patch/crop sizes from ivadomed and proceeded from there. The final center-cropping size is fixed to `64 x 192 x 320` to accommodate for larger SC diameter (on R-L) and larger spinal curvature (on A-P). `320` is the max size out of all the images in the training set (no cropping was done on S-I) direction.
