### ISSUE TITLE
Cleanup repos

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#62]
* remove [config/miccai2023](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/main/config/miccai2023)

TODO: continue the listing

**Comment by naga-karthik** [comment]
Update: PR #64 is active and is (aggressively) cleaning the repository.

**Comment by naga-karthik** [comment]
After the latest fix to the slow cloning of the repo https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/86, the repo is cleaned and downloads fast. 

Closing this issue!
