### ISSUE TITLE
One outlier subject in the softseg CSA of T1w contrast

### ISSUE THREAD

**Issue by naga-karthik** [sct-pipeline/contrast-agnostic-softseg-spinalcord#66]
I plotted the CSA of the softseg GTs from the latest preprocessed data found under `~/duke/projects/ivadomed/contrast-agnostic-seg/data_processed_sg_2023-08-08_NO_CROP/results`. The result is shown below - Note that there is one outlier subject in the plot which stretches the violin plot. 

<details>
<summary> per contrast GT CSA </summary>

<img width="535" alt="Screen Shot 2023-08-11 at 11 13 28 AM" src="https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/4653ef7b-6643-4406-b34f-e9e16eed78d8">

</details>

I looked at the .csv file `csa_soft_GT_T1w` for this contrast and the subject turns out to be `sub-oxfordFmrib04_T1w`. Below you can find how the softseg looks. It is indeed not complete and hence resulting in the outlier in the violin plot

<details>
<summary> outlier subject fsleyes</summary>

<img width="883" alt="Screen Shot 2023-08-11 at 11 10 55 AM" src="https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/47e1a688-583d-4dd6-8d16-d2a24f4b51b6">

</details>

The most surprising part is the model _learned this outlier_ and then predicted something similar in terms of the CSA. Below you can find the CSA of the model prediction

<details>
<summary> model prediction outlier</summary>

<img width="538" alt="Screen Shot 2023-08-11 at 11 19 07 AM" src="https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/53445351/810b26b5-b7e4-4ea3-af07-34ca010046c1">

</details>

I think this subject needs to be fixed. I showed this to @valosekj and we concluded that we should run the preprocessing again and do a thorough QC of the softsegs so that we eliminate any biases that any model will learn. 
tagging @sandrinebedard

**Comment by sandrinebedard** [comment]
From my investigations, this is beacause of the bad T1w registration to T2w. 

![anim](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/71230552/94769b33-ce71-4cc6-a1aa-218ab83e4b86)


We did not notice this since the old discs labels were also not proprely warped to the T1w space and thus did not include this half slice in the CSA computation...
The QC is over 1602 images to check, sorry if I missed that one :( 

Next steps:

- Remove frmi04 from git annex and add to exclude list
- Remove from preprocessed data

**Comment by sandrinebedard** [comment]
we don't need to re-run preprocessing, we can just delete this subject so you can retrain quickly! And I will pass the QC again next week (we can discuss it at tuesday's meeting too) to make sure this was the only one, sounds good?

**Comment by naga-karthik** [comment]
Yes, sounds good! I'll re-train over the weekend. 

Another way to do a robust QC would be also sort the `Mean(Area)` column in ascending order in the soft GT `.csv` files in the results folder of the preprocessed dataset and look for any subjects with abnormally high or low CSA. 

Jan and I quickly checked it and there was only `sub-oxfordFmrib04` with ~33 mm^2 but the others were okay. It would be better if you could take a look too!

**Comment by sandrinebedard** [comment]
great thanks! I'll take a look too!

**Comment by naga-karthik** [comment]
@sandrinebedard any updates on this? If you confirm that the QC for the latest version of the dataset is good then we can close this issue!

**Comment by sandrinebedard** [comment]
Now the subject  `sub-oxfordFmrib04` is in the exclude list: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/commit/bec11205428e0ab7c82f1715a6b7fbdcd9067eca
