### ISSUE TITLE
Add post-processing code to further improve prediction

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/contrast-agnostic-softseg-spinalcord#73]
E.g. remove small objects, etc. as done in ivadomed

**Comment by naga-karthik** [comment]
Thanks to @joshuacwnewton's help in [this PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4481), postprocessing is now possible within SCT and doesn't require any updates to the inference in this repo --> hence closing
